version: '3.8'

services:
  # Microservicio A
  backend-a:
    build: C:\Users\rodri\OneDrive\Escritorio\sumativa fullstack 3 backend\sumativafullstackbackend_usuarios\usuarios
    ports:
      - "8081:8080" # Puerto externo:interno
    networks:
      - mi-red-fullstack

  # Microservicio B
  backend-b:
    build: C:\Users\rodri\OneDrive\Escritorio\sumativa fullstack 3 backend\sumativafullstackbackend_laboratorio\laboratorio
    ports:
      - "8082:8080"
    networks:
      - mi-red-fullstack

    # Microservicio c
  backend-c:
    build: C:\Users\rodri\OneDrive\Escritorio\sumativa fullstack 3 backend\sumativafullstackbackend_resultados\resultados
    ports:
      - "8083:8080"
    networks:
      - mi-red-fullstack

  # Frontend Angular
  frontend:
    build: C:\Users\rodri\OneDrive\Escritorio\sumativa fullstack FrontEnd\actividad-sumativa-fullstack3-frontEnd\labconnect-frontend
    ports:
      - "80:80"
    depends_on:
      - backend-a
      - backend-b
    networks:
      - mi-red-fullstack

networks:
  mi-red-fullstack:
    driver: bridge